[tests] init
eventigo/eventigo-web pull request #22
Opened 2017-05-23 22:12 UTC by TomasVotruba

2017-05-24 09:11 UTC, TomasVotruba commented
I got only couple of minutes in the morning. Please check it if this covers the case in issue.
Gotta go now!

Thanks

2017-06-02 06:13 UTC, jakubzaba approved these changes

2017-06-02 12:31 UTC, filipsuk requested changes

2017-06-02 12:31 UTC, filipsuk commented on tests/Modules/Newsletter/Model/NewsletterServiceTest.php
> +        $this->assertSame('https://eventigo.cz/redirect/?url=someUrl', $this->linkGenerator->link('Front:Redirect:', ['someUrl']));
Minor detail: shouldn't we use base url from config?

2017-06-02 14:39 UTC, TomasVotruba commented on tests/Modules/Newsletter/Model/NewsletterServiceTest.php
> +        $this->assertSame('https://eventigo.cz/redirect/?url=someUrl', $this->linkGenerator->link('Front:Redirect:', ['someUrl']));
You're right. That would make test change proof.

2017-06-16 08:20 UTC, TomasVotruba commented on tests/Modules/Newsletter/Model/NewsletterServiceTest.php
> +        $this->assertSame('https://eventigo.cz/redirect/?url=someUrl', $this->linkGenerator->link('Front:Redirect:', ['someUrl']));
Fixed!

2017-06-19 12:30 UTC, filipsuk commented
@TomasVotruba is travis setup to run the tests? Does not seem like it to me. And also, if I run it on local, the test fails with :

```
There was 1 error:

1) App\Modules\Newsletter\Model\NewsletterServiceTest::testPrepareLinks
Error: Cannot access private property App\Modules\Newsletter\Model\NewsletterService::$context

/var/www/app/tests/Modules/Newsletter/Model/NewsletterServiceTest.php:47

--

There was 1 failure:

1) App\Modules\Newsletter\Model\NewsletterServiceTest::testRedirectLinks
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'https://eventigo.local/redirect/?url=someUrl'
+'http:///redirect/?url=someUrl'

/var/www/app/tests/Modules/Newsletter/Model/NewsletterServiceTest.php:39
```

However I am really looking forward to our first test 👍 🎉

2017-06-19 13:59 UTC, TomasVotruba commented
> @TomasVotruba is travis setup to run the tests? Does not seem like it to me. 

Ha! Good catch. Not really, fixed :+1: 

**Travis is passing now.** Only Scrutinizer is bugged, could you please remove it from [services in Settings](https://github.com/eventigo/eventigo-web/settings/installations)?

Also, I'd switch to [more reliable Coveralls](https://www.tomasvotruba.cz/blog/2017/06/12/how-to-require-minimal-code-coverage-for-github-pull-requests-with-coveralls/)

Could you [add the repository in there](https://coveralls.io/repos/new)?

2017-06-19 14:45 UTC, filipsuk commented
Great! I removed scrutinizer from settings, hopefully its gone. Could not add coveralls, their repo sync is kinda buggy, try to remind me later. Thanks for this!

2017-06-19 14:45 UTC, filipsuk approved these changes

2017-06-19 14:45 UTC, merged

2017-06-19 14:55 UTC, TomasVotruba commented
Thank you!

2017-06-20 06:51 UTC, TomasVotruba commented
@filipsuk Could you try today? It might be in better mood now :)

2017-06-20 08:32 UTC, filipsuk commented
@TomasVotruba ok repo is added to Coveralls, let me know if there is anything else I need to setup :)

2017-06-20 11:49 UTC, TomasVotruba commented
@filipsuk Thanks a lot :+1: