Add recently approved events to default newsletter
eventigo/eventigo-web pull request #29
Opened 2017-07-27 15:17 UTC by filipsuk

So far I had to build newsletter intro text html manually (usually contains new events).

Now fresh newsletter from newsletters:create command contains initial html intro with recently approved events ordered by size and start date. You are still able to do adjustments before send, however the process will be much faster.

2017-07-27 15:44 UTC, jakubzaba requested changes
Cool, great you started steps to the automation :) Can you take a look to a few format changes?

2017-07-27 15:44 UTC, jakubzaba commented on app/Modules/Core/Model/EventModel.php
> +    {
Put the bracket on the end of the line above pls.

2017-07-27 15:44 UTC, jakubzaba commented on app/Modules/Newsletter/Model/NewsletterService.php
> +        $newsletter->setIntroText($this->renderRecentlyApprovedEvents($this->getApprovedEventsSinceLastNewsletter()));
This line is hard to read. Can you format it this way
```
$newsletter->setIntroText(
    $this->renderRecentlyApprovedEvents(
        $this->getApprovedEventsSinceLastNewsletter()
    )
);
```

2017-07-27 15:44 UTC, jakubzaba commented on app/Modules/Core/Model/EventModel.php
> +    public function getApprovedEventsByDate(
Do you plan to use this method in the near future? How about make it simple as you need. No `$to` or `$orderByRate`?
The usage then would be way simpler.

2017-08-01 10:33 UTC, filipsuk commented
@jakubzaba Good points. God I miss prettier.

2017-08-01 10:36 UTC, jakubzaba approved these changes

2017-08-01 10:36 UTC, merged