Newsletter creation improvements
eventigo/eventigo-web pull request #9
Opened 2017-02-23 18:15 UTC by filipsuk

- New command to create default newsletter
- Few fixes around newsletters

2017-02-23 18:18 UTC, filipsuk commented
Should we remove this from parameters.neon?
```
        SendGrid:
		ApiKey: XXXX

	meetup:
		apiKey: XXXX
```

2017-02-23 18:20 UTC, jakubzaba requested changes
Small changes

2017-02-23 18:20 UTC, jakubzaba commented on app/Modules/Admin/Model/EventService.php
> +		$this->addTags($values->tags, (int)$event->id);
mezeru za (int)

2017-02-23 18:20 UTC, jakubzaba commented on app/Modules/Newsletter/Model/NewsletterService.php
> +	const CSS_FILE_PATH = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Presenters' . DIRECTORY_SEPARATOR .
Bych ty `DIRECTORY_SEPARATOR` už nepoužíval, nedá se to číst :)

2017-02-23 18:27 UTC, jakubzaba commented
@filipsuk Yes, should be in `template/config.local.neon`.

2017-02-23 23:28 UTC, filipsuk commented on app/Modules/Admin/Model/EventService.php
> +		$this->addTags($values->tags, (int)$event->id);
Is there a way to check this kind of code style issues in our cool CI tools? @TomasVotruba

2017-02-23 23:29 UTC, filipsuk commented on app/Modules/Newsletter/Model/NewsletterService.php
> +	const CSS_FILE_PATH = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Presenters' . DIRECTORY_SEPARATOR .
So just `/`? :)

2017-02-24 00:52 UTC, TomasVotruba commented on app/Modules/Newsletter/Model/NewsletterService.php
> +	const CSS_FILE_PATH = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Presenters' . DIRECTORY_SEPARATOR .
I would use `DIRECTORY_SEPARATOR`, it's per OS mess in time https://github.com/composer/composer/issues/6197

2017-02-24 00:53 UTC, TomasVotruba commented on app/Modules/Admin/Model/EventService.php
> +		$this->addTags($values->tags, (int)$event->id);
@filipsuk Yes! Working on it hard, coming soon, https://github.com/Symplify/Symplify/pull/81

2017-02-24 00:58 UTC, TomasVotruba requested changes

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Console/CreateNewsletterCommand.php
> +		$newsletterService = $this->getHelper('container')->getByType(NewsletterService::class);
Rather Ctor injection. This is just service locator.

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Console/CreateNewsletterCommand.php
> +class CreateNewsletterCommand extends Command
final

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Console/CreateNewsletterCommand.php
> +<?php declare(strict_types=1);
nice!

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Console/RenderNewslettersCommand.php
> +			->setDescription('Render users\' newsletters prepared to send');
I recommend avoiding this quota plays in any message if possible. Rephrase or use sprintf.
It's difficult to spot and can make some mess in output.

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Model/Entity/Newsletter.php
> +	 * @return string
These can be directly in return typehints. No need for it here.

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Model/NewsletterModel.php
> +	public function createNewsletter(Newsletter $newsletter)
Return type missing

2017-02-24 00:58 UTC, TomasVotruba commented on app/Modules/Newsletter/Presenters/templates/Newsletter/default.latte
> +        {$userNewsletter['content']|noescape}
Nice!

2017-02-24 00:58 UTC, TomasVotruba commented on app/config/extensions/console.neon
> +		tags: [kdyby.console.command]
Tags are often redundant information, I recommend them not using at all like this.
https://www.tomasvotruba.cz/blog/2017/02/12/drop-all-service-tags-in-your-nette-and-symfony-applications/

2017-02-24 00:58 UTC, TomasVotruba commented on composer.json
> +		"kdyby/facebook": "2.0.x-dev",
Just curious, what for?

2017-02-24 00:58 UTC, TomasVotruba commented
Very nice PR. Nice and clear to me, just enough code and obvious changes.

Thank you!

2017-02-24 01:00 UTC, TomasVotruba commented on app/Modules/Newsletter/Model/NewsletterService.php
> +	const CSS_FILE_PATH = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Presenters' . DIRECTORY_SEPARATOR .
Or just use method like `FileSystem::normalizePath()`. That's what I did in ApiGen for all paths possible.

Makes usage bulletproof for any OS programmer :)

2017-03-02 12:58 UTC, filipsuk commented on composer.json
> +		"kdyby/facebook": "2.0.x-dev",
because of this fix for Nette 2.4 https://github.com/Kdyby/Facebook/commit/a0752c43ed94b74663b975f240166d9aaa85ccca

2017-03-02 12:59 UTC, TomasVotruba approved these changes

2017-03-02 12:59 UTC, TomasVotruba commented
Beautifully clean!

2017-03-02 13:03 UTC, filipsuk commented on app/Modules/Newsletter/Model/Entity/Newsletter.php
> +	 * @return string
We are still running on PHP 7, not 7.1 (rosti.cz). So if I am correct, this could throw type errors when null.

2017-03-02 13:05 UTC, filipsuk commented on app/config/extensions/console.neon
> +		tags: [kdyby.console.command]
I suggest fixing this in another PR.

2017-03-02 14:06 UTC, jakubzaba approved these changes

2017-03-02 14:07 UTC, merged

2017-03-02 14:43 UTC, TomasVotruba commented on app/config/extensions/console.neon
> +		tags: [kdyby.console.command]
Good point